#ebean:
#  ddl:
#    generate: true
#    run: true
#    createOnly: true

datasource:
  db:
    url: jdbc:mysql://192.168.0.33:49006/daily?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: daily
    password: 123
    driver: com.mysql.cj.jdbc.Driver