server:
  port: 8080

  jetty:
    acceptors: 1
    selectors: 1
    min-threads: 1
    max-threads: 10
    thread-idle-timeout: 10s
    connection-idle-timeout: 60s

spring:
  application:
    name: daily
  profiles:
    active: production
    #    active: dev

  freemarker:
    suffix: .ftl
    request-context-attribute: request

  datasource:
    url: jdbc:mysql://192.168.0.33:49006/daily?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: daily
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    mapper.default-view-inclusion: true
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss