server:
  port: 8080

  jetty:
    acceptors: 1
    selectors: 1
    min-threads: 1
    max-threads: 10
    thread-idle-timeout: 10s
    connection-idle-timeout: 60s

spring:
  application:
    name: daily
  profiles:
    active: production
    #    active: dev

  jackson:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    mapper.default-view-inclusion: true
    time-zone: GMT+8
  mvc:
    view:
      prefix: /
      suffix: .jsp
    format:
      date: yyyy-MM-dd HH:mm:ss

#ebean:
#  ddl:
#    generate: true
#    run: true
#    createOnly: true

datasource:
  db:
    url: jdbc:mysql://49.233.77.33:49006/daily?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: daily
    password: 123
    driver: com.mysql.cj.jdbc.Driver