#ebean:
#  ddl:
#    generate: true
#    run: true
#    createOnly: true

datasource:
  db:
    url: jdbc:postgresql://192.168.0.33:5432/daily?useSSL=false
    username: daily
    password: jduioyiouq
    driver: org.postgresql.Driver